package definitions

type FieldName string

const (
	AlbumFieldID              FieldName = "id"
	AlbumFieldParentID        FieldName = "parent_id"
	AlbumFieldName            FieldName = "name"
	AlbumFieldDescription     FieldName = "description"
	AlbumFieldRank            FieldName = "rank"
	AlbumFieldAncestorIDs     FieldName = "ancestor_ids"
	AlbumFieldRuleJSON        FieldName = "rule_json"
	AlbumFieldCoverImageID    FieldName = "cover_image_id"
	AlbumFieldChildAlbumCount FieldName = "child_album_count"
	AlbumFieldImageCount      FieldName = "image_count"
	AlbumFieldACLLevel        FieldName = "acl_level"
	AlbumFieldACLUserID       FieldName = "acl_user_id"
	AlbumFieldUpdatedAt       FieldName = "updated_at"

	ImageFieldID           FieldName = "id"
	ImageFieldRoot         FieldName = "root"
	ImageFieldPath         FieldName = "path"
	ImageFieldFilename     FieldName = "filename"
	ImageFieldExt          FieldName = "ext"
	ImageFieldFileSize     FieldName = "file_size"
	ImageFieldMTime        FieldName = "mtime"
	ImageFieldFileHash     FieldName = "file_hash"
	ImageFieldMetaHash     FieldName = "meta_hash"
	ImageFieldTitle        FieldName = "title"
	ImageFieldCaption      FieldName = "caption"
	ImageFieldTakenAt      FieldName = "taken_at"
	ImageFieldCamera       FieldName = "camera"
	ImageFieldLens         FieldName = "lens"
	ImageFieldFocalLength  FieldName = "focal_length"
	ImageFieldAperture     FieldName = "aperture"
	ImageFieldExposure     FieldName = "exposure"
	ImageFieldISO          FieldName = "iso"
	ImageFieldLatitude     FieldName = "latitude"
	ImageFieldLongitude    FieldName = "longitude"
	ImageFieldRotation     FieldName = "rotation"
	ImageFieldRating       FieldName = "rating"
	ImageFieldWidth        FieldName = "width"
	ImageFieldHeight       FieldName = "height"
	ImageFieldPanorama     FieldName = "panorama"
	ImageFieldFocusX       FieldName = "focus_x"
	ImageFieldFocusY       FieldName = "focus_y"
	ImageFieldFocusMode    FieldName = "focus_mode"
	ImageFieldFocusSource  FieldName = "focus_source"
	ImageFieldExifJSON     FieldName = "exif_json"
	ImageFieldACLLevel     FieldName = "acl_level"
	ImageFieldACLUserID    FieldName = "acl_user_id"
	ImageFieldACLSource    FieldName = "acl_source"
	ImageFieldCreatedAt    FieldName = "created_at"
	ImageFieldUpdatedAt    FieldName = "updated_at"
	ImageFieldLastSeenSync FieldName = "last_seen_sync"
)
